### ISSUE TITLE
For ISBN13 calculate and validate,  when the checksum is 0 returned value is X instead 

### ISSUE THREAD

**Issue by mohsenBanan** [harens/checkdigit#171]
bookUtils.cs -i isbnCalculate13 978-1-960957-03
Returns X   --- instead of 0

bookUtils.cs -i isbnValidate13 978-1-960957-03-X  --- Returns True
bookUtils.cs -i isbnValidate13 978-1-960957-03-0  --- Returns False

978-1-960957-03-0 is a valid ISBN13.

Returning X instead of 0 seems to be by design, but why?

If it is not by design, then it is a bug.

P.S. bookUtils.cs is just a python command service that uses checkdigit.isbn

**Comment by harens** [comment]
Hey @mohsenBanan 👋

Thanks for using checkdigit and for opening this issue! You're completely right that this is a bug ([ISBN-13 shouldn't produce X as a check digit](https://stackoverflow.com/questions/2041511/can-a-valid-13-digit-isbn-have-x-as-one-of-characters)). I've pushed a commit that should fix this and I'll publish a new release shortly.

Thanks again for the bug report and for using checkdigit.

**Comment by harens** [comment]
@all-contributors please add @mohsenBanan for bug.
